Website updates2023
dsfsi/dsfsi.github.io pull request #88
Opened 2023-03-06 19:58 UTC by fiskanibanda

Final Dissertation posts - @vukosim

2023-03-07 06:17 UTC, vukosim commented on _posts/2023-03-06-Andani-dissertation.md
> +## Publications
See publication 

Andani Madodonga, Vukosi Marivate, and Matthew Adendorff. Izindaba-Tindzaba: Machine learning news categorisation for Long and Short Text for isiZulu and Siswati, *Journal of the Digital Humanities Association of Southern Africa *, 2023. [NLP] <> [[Paper URL](https://upjournals.up.ac.za/index.php/dhasa/article/view/4449)] DOI: [doi.org/10.55492/dhasa.v4i01.4449](https://dx.doi.org/doi.org/10.55492/dhasa.v4i01.4449)

2023-03-07 06:18 UTC, vukosim commented on _posts/2023-03-06-Yolanda-dissertation.md
> +## Publications
Maybe also embedd this video https://www.youtube.com/watch?v=GO3k72h9i0Q

2023-03-07 06:19 UTC, vukosim requested changes
See my comments

2023-03-07 11:48 UTC, fiskanibanda commented on _posts/2023-03-06-Yolanda-dissertation.md
> +## Publications
Added

2023-03-07 11:48 UTC, fiskanibanda commented on _posts/2023-03-06-Andani-dissertation.md
> +## Publications
Added

2023-03-08 07:46 UTC, vukosim approved these changes

2023-03-08 07:47 UTC, merged